[build]
  command = "sed -i \"s|API_URL|${API_URL}|g;s|API_TOKEN|${API_TOKEN}|g\" netlify.toml && npm run build"
  publish = 'public'
  functions = 'lambda/'

[dev]
  command = "sed -i \"s|API_URL|${API_URL}|g;s|API_TOKEN|${API_TOKEN}|g\" netlify.toml && yarn develop"
  publish = 'public'
  autoLaunch = true

[build.environment]
  YARN_VERSION = '1.22.10'
  YARN_FLAGS='--no-ignore-optional'

[context.develop]
  functions = "lambda/"

[[redirects]]
  from = "/api/*"
  to = "REPLACED_URL/:splat"
  status = 200
  force = true
  headers = {X-API-TOKEN = "REPLACED_TOKEN", X-From = "Netlify"}

[[headers]]
  for = "/static/*"

  [headers.values]
    Cache-Control = "public, max-age=360000"
