backend:
  name: github
  repo: credli/sourdough
  branch: main

local_backend: true
media_folder: static/img
# public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { name: templateKey, widget: hidden, default: 'blog-post' }
      - { label: 'Title', name: title, widget: string }
      - { label: 'Published Date', name: date, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: 'Featured Post', name: featuredPost, widget: boolean }
      - { label: 'Featured Image', name: featuredImage, widget: image }
      - { label: Body, name: body, widget: markdown }
      - { label: Tags, name: tags, widget: list }

  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: 'Landing Page'
        name: 'indexPage'
        fields:
          - { name: templateKey, widget: hidden, default: index-page }
          - {
              label: Carousel,
              name: carousel,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: Image, name: image, widget: image },
                  {
                    label: Actions,
                    name: actions,
                    required: false,
                    widget: list,
                    fields:
                      [
                        { label: Caption, name: caption, widget: string },
                        { label: Action, name: action, widget: string },
                        {
                          label: Type,
                          name: actionType,
                          widget: select,
                          options: ['primary', 'secondary'],
                          default: 'primary',
                        },
                      ],
                  },
                ],
            }
          - {
              label: 'Main Pitch',
              name: pitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }

      - file: src/pages/about/index.md
        label: 'About Page'
        name: 'aboutPage'
        fields:
          - { name: templateKey, widget: hidden, default: about-page }
          - { label: Title, name: title, widget: string }
          - { label: 'Sub Title', name: subTitle, widget: string }
          - { label: Body, name: body, widget: markdown }
          - {
              label: Mosaic,
              name: mosaic,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: src/pages/about/production.md
        label: 'Production'
        name: 'productionPage'
        fields:
          - { name: templateKey, widget: hidden, default: production-page }
          - { label: Title, name: title, widget: string }
          - { label: 'Sub Title', name: subTitle, widget: string }
          - { label: Body, name: body, widget: markdown }
          - {
              label: Mosaic,
              name: mosaic,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: src/pages/about/experience.md
        label: 'Experience'
        name: 'experiencePage'
        fields:
          - { name: templateKey, widget: hidden, default: experience-page }
          - { label: Title, name: title, widget: string }
          - { label: 'Sub Title', name: subTitle, widget: string }
          - { label: Body, name: body, widget: markdown }
          - {
              label: Mosaic,
              name: mosaic,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: src/pages/workshops/index.md
        label: 'Workshops'
        name: 'workshopsPage'
        fields:
          - { name: templateKey, widget: hidden, default: workshops-page }
          - { label: Title, name: title, widget: string }
          - { label: 'Sub Title', name: subTitle, widget: string }
          - {
              label: Benefits,
              name: benefits,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Benefit, name: benefit, widget: string },
                ],
            }
          - { label: Body, name: body, widget: markdown }
          - {
              label: Mosaic,
              name: mosaic,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          - { label: Rules, name: rules, widget: markdown }
          - {
              label: 'Cancellation Policy',
              name: cancellationPolicy,
              widget: markdown,
            }
      - file: src/pages/products/index.md
        label: 'Products Page'
        name: 'productsPage'
        fields:
          - { name: templateKey, widget: hidden, default: products-page }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: src/pages/categories/index.md
        label: 'Categories Page'
        name: 'categoriesPage'
        fields:
          - { name: templateKey, widget: hidden, default: categories-page }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

  - name: workshops
    label: Workshops
    label_singular: Workshop
    folder: src/pages/about/workshops
    create: true
    fields:
      - { name: templateKey, widget: hidden, default: workshop-details }
      - { label: Title, name: title, widget: string }
      - { label: From, name: from, widget: datetime }
      - { label: To, name: to, widget: datetime }
      - { label: Location, name: location, widget: string }
      - { label: Price, name: price, widget: number }
      - { label: Level, name: level, widget: string }
      - { label: prerequisite, name: Prerequisite, widget: string }
      - { label: Details, name: body, widget: markdown }

  - name: careers
    label: Careers
    label_singular: 'Job Posting'
    folder: src/pages/careers
    create: true
    fields:
      - { name: templateKey, widget: hidden, default: career-details }
      - { label: Title, name: title, widget: string }
      - { label: 'Published Date', name: date, widget: datetime }
      - { label: 'Job Type', name: type, widget: list, default: ['Full Time'] }
      - { label: Shift, name: shift, widget: string }
      - { label: Department, name: department, widget: string }
      - { label: Location, name: location, widget: string }
      - { label: Country, name: country, widget: string }
      - { label: Visible, name: visible, widget: boolean }
      - { label: Body, name: body, widget: markdown }

  - name: categories
    label: Categories
    label_singular: Cateogry
    folder: 'content/categories'
    create: true
    extension: json
    slug: '{{name}}'
    media_folder: 'img'
    fields:
      - { name: templateKey, widget: hidden, default: category }
      - { label: Name, name: name, widget: string }
      - { label: Rank, name: rank, widget: number, required: false }
      - { label: Image, name: image, widget: image }
      - { label: Icon, name: icon, widget: string, required: false }
      - {
          label: Description,
          name: description,
          widget: markdown,
          required: false,
        }

  - name: products
    label: Products
    label_singular: Product
    folder: 'content/products'
    create: true
    extension: json
    slug: '{{name}}'
    media_folder: 'img'
    fields:
      - { name: templateKey, widget: hidden, default: product }
      - { label: Name, name: name, widget: string }
      - { label: Rank, name: rank, widget: number, required: false }
      - { label: Summary, name: summary, widget: markdown }
      - { label: Schedule, name: schedule, widget: string, required: false }
      - { label: Price, name: price, widget: number }
      - {
          label: Images,
          name: images,
          widget: list,
          fields:
            [
              { label: Image, name: image, widget: image },
              {
                label: Description,
                name: description,
                widget: string,
                required: false,
              },
            ],
        }
      - {
          label: Attributes,
          name: attributes,
          widget: list,
          fields:
            [
              { label: Key, name: key, widget: string },
              { label: Value, name: value, widget: string },
              { label: Icon, name: icon, widget: string, required: false },
            ],
        }
