backend:
  name: github
  repo: credli/sourdough
  branch: main

local_backend: true
media_folder: static/img
public_folder: static/img

collections:
  - name: settings
    label: Settings
    files:
      - file: content/settings/site.json
        label: Site Settings
        name: 'siteSettings'
        fields:
          - {
              name: announcement,
              label: Announcement,
              widget: object,
              fields:
                [
                  { name: message, label: message, widget: text },
                  {
                    name: theme,
                    label: Theme,
                    widget: select,
                    options:
                      [
                        { label: 'Normal', value: 'primary' },
                        { label: 'Info', value: 'info' },
                        { label: 'Danger', value: 'danger' },
                      ],
                  },
                  {
                    name: visible,
                    label: Show,
                    widget: boolean,
                    default: false,
                  },
                ],
            }
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { name: templateKey, widget: hidden, default: 'blog-post' }
      - { label: 'Title', name: title, widget: string }
      - { label: 'Published Date', name: date, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: 'Featured Post', name: featuredPost, widget: boolean }
      - { label: 'Featured Image', name: featuredImage, widget: image }
      - { label: Body, name: body, widget: markdown }
      - { label: Tags, name: tags, widget: list }

  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: 'Landing Page'
        name: 'indexPage'
        fields:
          - { name: templateKey, widget: hidden, default: index-page }
          - {
              label: Carousel,
              name: carousel,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: Image, name: image, widget: image },
                  {
                    label: Actions,
                    name: actions,
                    required: false,
                    widget: list,
                    fields:
                      [
                        { label: Caption, name: caption, widget: string },
                        { label: Action, name: action, widget: string },
                        {
                          label: Type,
                          name: actionType,
                          widget: select,
                          options: ['primary', 'secondary'],
                          default: 'primary',
                        },
                      ],
                  },
                ],
            }
          - {
              label: 'Main Pitch',
              name: pitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }

      - file: src/pages/about/index.md
        label: 'About Page'
        name: 'aboutPage'
        fields:
          - { name: templateKey, widget: hidden, default: about-page }
          - { label: Title, name: title, widget: string }
          - { label: 'Sub Title', name: subTitle, widget: string }
          - { label: Body, name: body, widget: markdown }
          - {
              label: Mosaic,
              name: mosaic,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: src/pages/about/production.md
        label: 'Production'
        name: 'productionPage'
        fields:
          - { name: templateKey, widget: hidden, default: production-page }
          - { label: Title, name: title, widget: string }
          - { label: 'Sub Title', name: subTitle, widget: string }
          - { label: Body, name: body, widget: markdown }
          - {
              label: Mosaic,
              name: mosaic,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: src/pages/about/experience.md
        label: 'Experience'
        name: 'experiencePage'
        fields:
          - { name: templateKey, widget: hidden, default: experience-page }
          - { label: Title, name: title, widget: string }
          - { label: 'Sub Title', name: subTitle, widget: string }
          - { label: Body, name: body, widget: markdown }
          - {
              label: Mosaic,
              name: mosaic,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: src/pages/workshops/index.md
        label: 'Workshops'
        name: 'workshopsPage'
        fields:
          - { name: templateKey, widget: hidden, default: workshops-page }
          - { label: Title, name: title, widget: string }
          - { label: 'Sub Title', name: subTitle, widget: string }
          - {
              label: Benefits,
              name: benefits,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Benefit, name: benefit, widget: string },
                ],
            }
          - { label: Body, name: body, widget: markdown }
          - {
              label: Mosaic,
              name: mosaic,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          - { label: Rules, name: rules, widget: markdown }
          - {
              label: 'Cancellation Policy',
              name: cancellationPolicy,
              widget: markdown,
            }

  - name: workshops
    label: Workshops
    label_singular: Workshop
    folder: src/pages/about/workshops
    create: true
    fields:
      - { name: templateKey, widget: hidden, default: workshop-details }
      - { label: Title, name: title, widget: string }
      - { label: From, name: from, widget: datetime }
      - { label: To, name: to, widget: datetime }
      - { label: Location, name: location, widget: string }
      - { label: Price, name: price, widget: number }
      - { label: Level, name: level, widget: string }
      - { label: prerequisite, name: Prerequisite, widget: string }
      - { label: Details, name: body, widget: markdown }

  - name: careers
    label: Careers
    label_singular: 'Job Posting'
    folder: src/pages/careers
    create: true
    fields:
      - { name: templateKey, widget: hidden, default: career-details }
      - { label: Title, name: title, widget: string }
      - { label: 'Published Date', name: date, widget: datetime }
      - {
          label: 'Job Type',
          name: type,
          widget: select,
          options:
            ['Full-time', 'Part-time', 'Internship', 'Per hour', 'Consultancy'],
          default: ['Full Time'],
        }
      - { label: Shift, name: shift, widget: string }
      - { label: Department, name: department, widget: string }
      - { label: Location, name: location, widget: string }
      - { label: Country, name: country, widget: string }
      - { label: Visible, name: visible, widget: boolean }
      - { label: Body, name: body, widget: markdown }

  - name: category
    label: Categories
    label_singular: Category
    folder: content/categories
    format: json
    slug: '{{fields.slug}}'
    path: '{{slug}}'
    create: true
    sortable_fields: ['menuOrder']
    media_folder: 'images'
    public_folder: 'images/'
    fields:
      - { name: templateKey, widget: hidden, default: category }
      - { name: slug, label: Slug }
      - { name: name, label: Name }
      - { name: description, label: Description, widget: text }
      - { name: menuOrder, label: 'Menu Order', widget: number }
      - { name: image, label: Image, widget: image }

  - name: product
    label: Products
    label_singular: Product
    folder: content/products
    format: json
    slug: '{{fields.slug}}'
    path: '{{slug}}'
    create: true
    media_folder: 'images'
    public_folder: 'images/'
    fields:
      - { name: templateKey, widget: hidden, default: product }
      - { name: name, label: Name }
      - { name: slug, label: Slug }
      - { name: description, label: Description, widget: markdown }
      - {
          name: categories,
          label: Categories,
          widget: relation,
          collection: category,
          search_fields: ['name'],
          display_fields: ['name'],
          value_field: '{{slug}}',
          multiple: true,
        }
      - { name: image, label: Image, widget: image }
      - {
          name: gallery,
          label: 'Image Gallery',
          widget: list,
          fields:
            [
              { name: image, label: Image, widget: image },
              { name: title, label: Title },
            ],
        }
      - {
          name: leadTime,
          label: 'Lead Time (hours)',
          widget: number,
          required: false,
          default: 24,
        }
      - { name: outOfStock, label: 'Out of Stock', widget: boolean }
      - {
          name: attributes,
          label: Attributes,
          widget: list,
          fields:
            [
              { name: title, label: Title },
              { name: details, label: Details },
              { name: icon, label: Icon, widget: image, required: false },
            ],
        }
      - {
          name: variants,
          label: Variants,
          widget: list,
          fields:
            [
              { name: name, label: Name },
              { name: slug, label: Slug },
              {
                name: description,
                label: Description,
                widget: markdown,
                required: false,
              },
              { name: outOfStock, label: 'Out of Stock', widget: boolean },
              { name: image, label: Image, widget: image },
            ],
        }
      - {
          name: options,
          label: 'Product Options',
          widget: relation,
          collection: productOption,
          search_fields: ['name'],
          display_fields: ['name'],
          value_field: '{{slug}}',
          multiple: true,
          required: false,
        }
      - {
          name: menuOrder,
          label: 'Menu Order',
          widget: number,
          required: false,
        }
      - { name: createdAt, widget: datetime, required: false }

  - name: productOption
    label: 'Product Options'
    label_singular: 'Option'
    folder: 'content/product-options'
    format: json
    slug: '{{fields.slug}}'
    path: '{{slug}}'
    create: true
    fields:
      - { name: templateKey, widget: hidden, default: productOption }
      - { name: slug, label: Slug }
      - { name: name, label: Name }
      - { name: required, label: Required, widget: boolean }
      - { name: description, label: Description, required: false }
      - {
          name: type,
          label: 'Option Type',
          widget: select,
          options:
            [
              { label: 'Pick one', value: 'radio' },
              { label: 'Multiple Choice', value: 'checkbox' },
              { label: 'Short Answer', value: 'string' },
              { label: 'Long Answer', value: 'text' },
            ],
        }
      - {
          name: options,
          label: 'Options',
          widget: list,
          fields:
            [
              { name: label, label: Label },
              { name: value, label: Value, default: '', required: false },
              { name: selected, label: Selected, widget: boolean },
            ],
        }
